# Generated by Django 4.2.7 on 2023-11-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstSectionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductImage', models.ImageField(upload_to='media')),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductPrice', models.CharField(max_length=100)),
            ],
        ),
    ]
