# Generated by Django 4.2.7 on 2023-11-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_secondsectionproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstsectionproduct',
            name='ProductPrice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='secondsectionproduct',
            name='ProductPrice',
            field=models.IntegerField(),
        ),
    ]
