# Generated by Django 4.2.7 on 2023-11-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_thirdsectionproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoSectionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LogoImage', models.ImageField(upload_to='media')),
            ],
        ),
    ]
