# Generated by Django 4.2.7 on 2023-11-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_logosectionproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBannerFirst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BannerImage', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBannerSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BannerImage', models.ImageField(upload_to='media')),
            ],
        ),
    ]
