# Generated by Django 4.2.7 on 2023-11-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_productbannerfirst_firsttitle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FourthSectionProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ProductImage", models.ImageField(upload_to="media")),
                ("ProductName", models.CharField(max_length=100)),
                ("ProductPrice", models.IntegerField()),
            ],
        ),
    ]
