# Generated by Django 4.2.7 on 2023-11-13 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_gamecart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gamecart',
            new_name='gamecartsection',
        ),
    ]
