# Generated by Django 4.2.7 on 2023-11-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0015_alter_product_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductBannerFirst",
        ),
        migrations.DeleteModel(
            name="ProductBannerSecond",
        ),
        migrations.AddField(
            model_name="category",
            name="display_in_home",
            field=models.BooleanField(default=False),
        ),
    ]
