# Generated by Django 4.2.7 on 2023-11-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0016_delete_productbannerfirst_delete_productbannersecond_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="gamecartsection",
        ),
        migrations.DeleteModel(
            name="gamecartsectiontwo",
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
